### ISSUE TITLE
Dynamic feature recognition

### ISSUE THREAD

**Issue by YongshuaiZ** [HJMGARMIN/OVD-SLAM#1]
hello author！Is the dynamic feature recognition part inconsistent with the paper?

**Comment by HJMGARMIN** [comment]
> hello author！Is the dynamic feature recognition part inconsistent with the paper?

yes，I have explained it in readme.txt. Because some methods in the paper are corporated with a company, they may be used in a commercial product. We are not allowed open source it. Instead, we released a version which can make similar performance.

**Comment by HJMGARMIN** [comment]
After I complete the corporation, I will released all non-commercial parts finally.



---Original---
From: ***@***.***&gt;
Date: Tue, May 23, 2023 09:36 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HJMGARMIN/OVD-SLAM] Dynamic feature recognition (Issue #1)




 
Closed #1 as completed.

**Comment by YongshuaiZ** [comment]
Thank you so much for your replay！I am looking forward to the final version.
