### ISSUE TITLE
您好，您论文的关于深度值的卡方公式可以帮我解答一下吗

### ISSUE THREAD

**Issue by dabaonideluan** [HJMGARMIN/OVD-SLAM#10]
![b5c7a295aa93b5490a94e41adce02ea](https://github.com/HJMGARMIN/OVD-SLAM/assets/91612012/8e03e09e-aa81-4419-ab75-c88070531e3a)
这个公式按照我的理解应该是把一个高斯分布转化成标准高斯分布计算卡方值，那分母应该是计算标准差。是否少了一个1/n？另外，计算标准差的话，分母是否也不需要平方了？

**Comment by HJMGARMIN** [comment]
这个公式确实有编辑错误，以你对标准差的理解为准就可以，分母需要再做一个开方，可以看代码里面的具体实现，代码里面这部分公式是没有问题的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月5日(周一) 凌晨1:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HJMGARMIN/OVD-SLAM] 您好，您论文的关于深度值的卡方公式可以帮我解答一下吗 (Issue #10)




 
b5c7a295aa93b5490a94e41adce02ea.png (view on web)
 这个公式按照我的理解应该是把一个高斯分布转化成标准高斯分布计算卡方值，那分母应该是计算标准差。是否少了一个1/n？另外，计算标准差的话，分母是否也不需要平方了？

**Comment by HJMGARMIN** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月5日(周一) 凌晨1:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HJMGARMIN/OVD-SLAM] 您好，您论文的关于深度值的卡方公式可以帮我解答一下吗 (Issue #10)




 
b5c7a295aa93b5490a94e41adce02ea.png (view on web)
 这个公式按照我的理解应该是把一个高斯分布转化成标准高斯分布计算卡方值，那分母应该是计算标准差。是否少了一个1/n？另外，计算标准差的话，分母是否也不需要平方了？

**Comment by HJMGARMIN** [comment]
更正如下
![image](https://github.com/HJMGARMIN/OVD-SLAM/assets/52454672/407c12e5-11a0-4d18-9b73-82ad8766a8d4)

**Comment by dabaonideluan** [comment]
好的好的，十分感谢！
