### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by selfInnovator** [HJMGARMIN/OVD-SLAM#2]
Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Initialization of Atlas from scratch 
Creation of new map with id: 0
Creation of new map with last KF id: 0
Seq. Name: 
load model success
There are 1 cameras in the atlas
Camera 0 is pinhole
0.01 50 1
load model success

-------
Start processing sequence ...
Images in the sequence: 827

First KF:0; Map init KF:0
New Map created with 1071 points
Starting the Viewer
the above is running prompt, i find the running result does not reject dynamic object, its running result is consistent with ORB-SLAM3.
Could answer me, thank you.

**Comment by selfInnovator** [comment]
by theway,I export engine by meself.

**Comment by HJMGARMIN** [comment]
Please provide your yaml file.

**Comment by selfInnovator** [comment]
%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 535.4
Camera1.fy: 539.2
Camera1.cx: 320.1
Camera1.cy: 247.6

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
Stereo.b: 0.2247

# Depth map values factor
RGBD.DepthMapFactor: 5000.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

UseDynamic: 1
PointCloudMapping: 1
PointCloudMapping.Resolution: 0.01
meank: 50
thresh: 1.0 this is TUM3.yaml

**Comment by HJMGARMIN** [comment]
Do you use the engine files provided by me? If not, please check the output of YOLO thread.
