### ISSUE TITLE
Noisy Depth in Bonn Dataset

### ISSUE THREAD

**Issue by rwn17** [HJMGARMIN/OVD-SLAM#3]
Hi @HJMGARMIN,

Thanks for your excellent work! I was wondering did you notice any noise in depth from the Bonn dataset (shown in the attached figure, especially the wall and table)? 
![Screenshot from 2023-07-13 20-08-00](https://github.com/HJMGARMIN/OVD-SLAM/assets/54616858/69924465-16e1-4a08-a701-51d284c92ea6)

Following is the code for visualization

```
import open3d as o3d
import numpy as np


H = 480
W = 640
fx = 542.822841
fy = 542.576870
cx = 315.593520
cy = 237.756098


K = o3d.camera.PinholeCameraIntrinsic(
    width=W,
    height=H,
    fx=fx,
    fy=fy,
    cx=cx,
    cy=cy
)

depth_file = '/home/weining/Downloads/rgbd_bonn_balloon/depth/1548266469.88217.png'
depth_img = o3d.io.read_image(depth_file)
points = o3d.geometry.PointCloud.create_from_depth_image(
    depth = depth_img,
    intrinsic = K,
    depth_scale = 5000,
)

o3d.visualization.draw_geometries([points])
```

Thanks in advance!
Weining

**Comment by HJMGARMIN** [comment]
Do you mean that the noise of wall and desk influences the localization of SLAM system? In my project, I just use the depth map to transform 2D points to 3D points. The depth was captured by authors of Bonn dataset, I did not make any change. Depth information from RGB-D camera indoor is more likely to be accurate.

**Comment by rwn17** [comment]
Indeed, I've observed that the depth data in the original Bonn dataset tend to be fairly noisy. This is particularly noticeable in textureless regions and along the image boundaries. My assumption is that these issues may arise from the quality of the data capture device. I was wondering if have you conducted any similar quality checks or evaluations on this dataset by any chance?

**Comment by HJMGARMIN** [comment]
Just use the original depth images in any RGB-D SLAM task. I did not consider the quality of the depth, it is accurate enough for localization and mapping in my system.
