### ISSUE TITLE
稠密重建

### ISSUE THREAD

**Issue by foxlock5254** [HJMGARMIN/OVD-SLAM#4]
大佬您好，感谢开源，我看都是国人，我就用中文了，我想问一下运行哪个程序可以实现稠密重建的效果？我运行了rgbd_tum，跑数据集没有看到稠密建图的结果。

**Comment by HJMGARMIN** [comment]
将对应yaml文件里面的 PointCloudMapping: 0 设置为 1

**Comment by foxlock5254** [comment]
大佬您好，我照您说的该了PointCloudMapping后，结果是这样
![Screenshot from 2023-07-29 16-36-37](https://github.com/HJMGARMIN/OVD-SLAM/assets/74046665/d2c9fc51-da0c-4e1a-ab8b-5f188186ec10)

人物没有框出来，稠密的图也不对

**Comment by foxlock5254** [comment]
我是这样运行的./rgbd_tum ../../Vocabulary/ORBvoc.bin ./TUM3.yaml /home/nan/Downloads/orbslam3_datasats/rgbd_dataset_freiburg3_walking_xyz /home/nan/Downloads/orbslam3_datasats/rgbd_dataset_freiburg3_walking_xyz/associate.txt

**Comment by HJMGARMIN** [comment]
人的框没有写，可以自己写一下可视化，稠密图需要滑动滚轮才能看见

**Comment by HJMGARMIN** [comment]
而且从图里来看，你yaml文件里面的UseDynamic没有开

**Comment by foxlock5254** [comment]
大佬您好，这个稠密图里面人物没有剔除，是我哪里没操作好吗？
![Screenshot from 2023-07-29 16-44-26](https://github.com/HJMGARMIN/OVD-SLAM/assets/74046665/038ea512-d9e1-48dc-8d83-5cabb44bc0f5)

**Comment by HJMGARMIN** [comment]
![image](https://github.com/HJMGARMIN/OVD-SLAM/assets/52454672/127cee2d-2f68-4ae5-90ef-e89593ec8300)
我这边测试是没有问题的

**Comment by foxlock5254** [comment]
您是用的哪个yaml文件呢
