### ISSUE TITLE
run problems

### ISSUE THREAD

**Issue by CoderDoubleTen** [HJMGARMIN/OVD-SLAM#5]
Camera1.k3 optional parameter does not exist...
-Loaded camera 1
Camera.newHeight optional parameter does not exist...
Camera.newWidth optional parameter does not exist...
-Loaded image info
-Loaded RGB-D calibration
-Loaded ORB settings
Viewer.imageViewScale optional parameter does not exist...
-Loaded viewer settings
System.LoadAtlasFromFile optional parameter does not exist...
System.SaveAtlasToFile optional parameter does not exist...
-Loaded Atlas settings
System.thFarPoints optional parameter does not exist...
-Loaded misc parameters
SLAM settings:
-Camera 1 parameters (Pinhole): [ 535.4 539.2 320.1 247.6 ]
-Camera 1 distortion parameters: [ 0 0 0 0 ]
-Original image size: [ 640 , 480 ]
-Current image size: [ 640 , 480 ]
-Sequence FPS: 30
-RGB-D depth map factor: 5000
-Features per image: 1500
-ORB scale factor: 1.2
-ORB number of scales: 8
-Initial FAST threshold: 20
-Min FAST threshold: 7

Loading ORB Vocabulary. This could take a while...
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
已放弃

**Comment by HJMGARMIN** [comment]
I have changed the vocabulary file from txt to bin. Therefore, please use "./Vocabulary/ORBvoc.bin"

**Comment by CoderDoubleTen** [comment]
thanks!!!

**Comment by CoderDoubleTen** [comment]
![jieguo](https://github.com/HJMGARMIN/OVD-SLAM/assets/57647569/f17c5c48-cde5-436e-9629-473e89afd733)
请问我运行结果怎么只有这两个窗口，而且没有剔除掉动态点，好像就是原本的orb-slam3的效果，请问原本的运行结果是什么呢？谢谢

**Comment by HJMGARMIN** [comment]
看一下你yaml文件，里面设置了是否去除动态和稠密建图的开关

**Comment by CoderDoubleTen** [comment]
请问一下是哪个yaml文件呢？我只使用了TUM3.yaml,里面也没有发现控制开关呀

**Comment by HJMGARMIN** [comment]
https://github.com/HJMGARMIN/OVD-SLAM/blob/afca45de6eee3bdac4bd7c2ad33add9f56ee100d/Examples/RGB-D/TUM3.yaml#L71

**Comment by CoderDoubleTen** [comment]
非常感谢！谢谢！！！

**Comment by CoderDoubleTen** [comment]
请问一下按照你的源码，我xyz数据集跑出来的std  为0.010，rmse为0.018.跟你论文的实验数据差了不少，请问能帮我分析一下是什么原因吗？谢谢

**Comment by HJMGARMIN** [comment]
需要调参的，特征点数量等等各种参数都会影响，而且我发布的代码为在原始ORB-SAM3的基础上进行修改的，并没有根据论文的源代码刻意调整参数，而且因为项目协议的问题并不能发布全部代码，只能给出一个相近的实现思路
